# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vde-vasc <vde-vasc@student.42.rio>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/22 13:08:00 by vde-vasc          #+#    #+#              #
#    Updated: 2023/07/29 09:37:25 by vde-vasc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = animal

CXX	=	c++

CFLAGS = -Wall -Wextra -Werror

SRCS = main.cpp WrongCat.cpp WrongAnimal.cpp Animal.cpp Cat.cpp Dog.cpp

all: $(NAME)

$(NAME): ${SRCS}
	${CXX} ${CFLAGS} ${SRCS} -o $(NAME)

clean:
	@rm -rf ${NAME}

fclean: clean
	@rm -rf ${NAME}

re: fclean all

.PHONY: all re fclean clean 
